version: '3'

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.2.4
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:password@localhost/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    _PIP_ADDITIONAL_REQUIREMENTS: pandas==1.1.5 PyMySQL==1.0.2 requests==2.27.1 mysql-connector-python==8.0.28
  volumes:
    - ./yts-movies-etl/Airflow/dags:/opt/airflow/dags
    - ./yts-movies-etl/Airflow/logs:/opt/airflow/logs
    - ./yts-movies-etl/Airflow/plugins:/opt/airflow/plugins
    - ./yts-movies-etl/Airflow/etl_operators:/opt/airflow/etl_operators
  user: root
  
services:
      
  airflow-webserver:
    container_name: airflow_webserver
    <<: *airflow-common
    command: webserver
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - airflow-init
       
  airflow-scheduler:
    container_name: airflow_scheduler
    <<: *airflow-common
    command: scheduler
    restart: unless-stopped

    depends_on:
      - airflow-init